export const JobKeywords=[
    "Gynecologist",
    "Pediatrician",
    "Critical Care",
    "Anaesthesiologist",
    "Cardiologist",
    "GI Surgeon",
    "Neurosurgeon",
    "Nephrologist",
    "Gastroenterologist",
    "Internal Medicine",
    "Radiologist",
    "General Surgeon",
    "Orthopedic",
    "Cardiac Anesthesia",
    "Emergency Medicine",
    "Interventional Radiologist",
    "Urologist",
    "Gastro Surgeon",
    "CTVS Surgeon",
    "Surgical Oncologist",
    "Medical Oncologist",
    "Plastic Surgeon",
    "Haematopathologist",
    "Pathologist",
    "Opthamologist",
    "V R Surgeon"
  ];
  
export const LocationKeywords=[
    "Bangalore",
    "Delhi NCR",
    "Mumbai",
    "South Delhi",
    "Navi Mumbai",
    "Warangal",
    "Hyderabad",
    "Punjab",
    "Hisar",
    "Dhanbad",
    "Pune",
    "Jalandhar",
    "Sagar",
    "Gwalior",
    "Neemrana",
    "Hansi Haryana",
    "Jhujhunu",
    "Gurgaon",
    "Kaushambhi Ghaziabad",
    "Faridabad",
    "Central Delhi",
    "Greater Noida",
    "Bhopal",
    "Indore",
    "Amritsar",
    "North Delhi",
    "Kanpur",
    "Patna",
    "Ranchi",
    "Sirsa",
    "Saharanpur",
    "Haldwani",
    "Bhubneshwer",
    "Ahmedabad",
    "Vadodra"
  ];
  